### ISSUE TITLE
can't register

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#40]
In this page:
http://djangoupgrade.buddhistexchange.com/accounts/signup/
Enter valid information, click complete registration button, receive:
IntegrityError at /accounts/signup/
null value in column "last_login" violates not-null constraint
Request Method:	POST
Request URL:	http://djangoupgrade.buddhistexchange.com/accounts/signup/
Django Version:	1.10.5
Exception Type:	IntegrityError
Exception Value:	
null value in column "last_login" violates not-null constraint
Exception Location:	/home/befree/.virtualenvs/be_upgrade/lib/python3.5/site-packages/django/db/backends/utils.py in execute, line 64
Python Executable:	/usr/local/bin/python3
Python Version:	3.5.2
Python Path:	
['/home/befree/webapps/be_djangoupgrade',
 '/home/befree/webapps/be_djangoupgrade/myproject',
 '/home/befree/.virtualenvs/be_upgrade/lib/python3.5/site-packages',
 '/usr/local/lib/python35.zip',
 '/usr/local/lib/python3.5',
 '/usr/local/lib/python3.5/plat-linux',
 '/usr/local/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/site-packages']
Server time:	Tue, 24 Jan 2017 16:35:13 -0600

**Comment by vaimdev** [comment]
Just tested, no longer have this problem.
