### ISSUE TITLE
Exception when clicks on Confirm order button

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#45]
First register an account, then in homepage clicks on Add to Bag button, then click on Cart menu in the top right corner. If you didn't fill in mailing address, you are directed to profile page in My Account. After you fill in mailing information and clicked save, you are redirected to Orders In your card page. You click on Confirm Order button, and receive below exception:

AttributeError at /check_out/
module 'django.db.transaction' has no attribute 'commit_on_success'
Request Method:	POST
Request URL:	http://djangoupgrade.buddhistexchange.com/check_out/
Django Version:	1.10.5
Exception Type:	AttributeError
Exception Value:	
module 'django.db.transaction' has no attribute 'commit_on_success'
Exception Location:	/home/befree/webapps/be_djangoupgrade/myproject/core/views.py in check_out, line 311
Python Executable:	/usr/local/bin/python3
Python Version:	3.5.2
Python Path:	
['/home/befree/webapps/be_djangoupgrade',
 '/home/befree/webapps/be_djangoupgrade/myproject',
 '/home/befree/.virtualenvs/be_upgrade/lib/python3.5/site-packages',
 '/usr/local/lib/python35.zip',
 '/usr/local/lib/python3.5',
 '/usr/local/lib/python3.5/plat-linux',
 '/usr/local/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/site-packages']
Server time:	Thu, 26 Jan 2017 07:16:37 -0600

**Comment by vaimdev** [comment]
Fixed

**Comment by sabrinasun** [comment]
This looks better now. However email are not sending any more, used to send email before latest fixes. When I was testing the first round of upgrade, email was sent I believe. I open another issue for this.
