### ISSUE TITLE
change email thrown exception

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#46]
Login, click on My account -> Change Email ->enter a new email address, click on Change Email button, receive:

RelatedObjectDoesNotExist at /accounts/befree/email/
User has no userena_signup.
Request Method:	POST
Request URL:	http://djangoupgrade.buddhistexchange.com/accounts/befree/email/
Django Version:	1.10.5
Exception Type:	RelatedObjectDoesNotExist
Exception Value:	
User has no userena_signup.
Exception Location:	/home/befree/.virtualenvs/be_upgrade/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py in __get__, line 370
Python Executable:	/usr/local/bin/python3
Python Version:	3.5.2
Python Path:	
['/home/befree/webapps/be_djangoupgrade',
 '/home/befree/webapps/be_djangoupgrade/myproject',
 '/home/befree/.virtualenvs/be_upgrade/lib/python3.5/site-packages',
 '/usr/local/lib/python35.zip',
 '/usr/local/lib/python3.5',
 '/usr/local/lib/python3.5/plat-linux',
 '/usr/local/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/site-packages']
Server time:	Thu, 26 Jan 2017 15:49:27 -0600

**Comment by vaimdev** [comment]
Fixed
