### ISSUE TITLE
Add author throw exception = Now issue is Stylesheet missing, validation message is not displayed

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#47]
login, click on My Inventory, click on Add Book button, in the add book page click on Add author link, a window is popped up with exception: 
NameError at /add/author/
name 'get_models' is not defined
Request Method:	GET
Request URL:	http://djangoupgrade.buddhistexchange.com/add/author/
Django Version:	1.10.5
Exception Type:	NameError
Exception Value:	
name 'get_models' is not defined
Exception Location:	/home/befree/webapps/be_djangoupgrade/myproject/core/views.py in add_new_model, line 585
Python Executable:	/usr/local/bin/python3
Python Version:	3.5.2
Python Path:	
['/home/befree/webapps/be_djangoupgrade',
 '/home/befree/webapps/be_djangoupgrade/myproject',
 '/home/befree/.virtualenvs/be_upgrade/lib/python3.5/site-packages',
 '/usr/local/lib/python35.zip',
 '/usr/local/lib/python3.5',
 '/usr/local/lib/python3.5/plat-linux',
 '/usr/local/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/site-packages']
Server time:	Thu, 26 Jan 2017 16:35:28 -0600

**Comment by vaimdev** [comment]
Fixed

**Comment by sabrinasun** [comment]
![addauthorstyle](https://cloud.githubusercontent.com/assets/877632/22574667/462e2354-e97e-11e6-910d-dc90cb44b32e.png)
First login, then go to
http://djangoupgrade.buddhistexchange.com/account/material/new/
Now click on Add Author, the popup is displayed. 
However, if compare with production, style is missing. When just click on save button without doing anything, error message is not displayed. Above is a screenshot from production.

**Comment by vaimdev** [comment]
Fixed
