### ISSUE TITLE
Send email is not quite working.

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#48]

**Comment by sabrinasun** [comment]
Used to send email when I was testing on vacation. Easiest way to try is to login as sabrinanyu@gmail.com/ilucky, and then click on Books I need to send. Click on Contact Reader links. Write something and click send.  
Email  is globally not working.

**Comment by vaimdev** [comment]
I have fixed it to use the SMTP settings same as production server. 
A test email sending to "befree/Buddhist Exchange" 

Should be fixed now.

**Comment by sabrinasun** [comment]
This used to work before second round of change, something was changed?

**Comment by vaimdev** [comment]
Nothing was changed for email sending before second round. It was using the sabrinayu@gmail.com to send out email before I fix it. Maybe you change the password recently ?

Is it working now ? I did send an email to the befree user but I can't confirm whether you received it or not.
