### ISSUE TITLE
Can't submit link and text form

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#53]
There are two forms, link and text form. When click on the submit button, there is neither error message or page refresh.  Well occasionally it goes through. See error in console log, same for both forms.  Same error for comments. 
![submit error message](https://cloud.githubusercontent.com/assets/877632/23881519/578499ea-0831-11e7-96ae-24776221da26.png)

**Comment by sabrinasun** [comment]
![submit error message](https://cloud.githubusercontent.com/assets/877632/23881514/43dea87c-0831-11e7-9f23-8e61f272ade1.png)

**Comment by vaimdev** [comment]
Hi Sabrina, I have done initial checking. The first "django is not defined" is an error from original code which does not affect functionality , however, I have fixed it now.

"PostForm is not defined" error will be fixed together with other bugs.
