### ISSUE TITLE
Issues with Topics list dislay

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#54]
1. There is a  &nbsp; htm code infront of the first keyword in the keyword list section. Please remove it so that the first keyword is left aligned. 

2. Please display the currently selected topic with below style,  remove the underline. 
{
    background: #f7cd80;
    padding: 3px;
    text-decoration: none;
    color: black;
}
Apply the same style for All Topics when selected. 

issue with topic  space trim issue is addressed  in a different bug

**Comment by vaimdev** [comment]
noted. will change

**Comment by vaimdev** [comment]
Issues fixed.
Issue 1 is data problem , already patch data.
Issue 2 , done.

**Comment by sabrinasun** [comment]
Still some issue with issue 1. Seems there is a topic which is empty string, not sure what is that. 
![left menu](https://cloud.githubusercontent.com/assets/877632/24386041/652975c4-133b-11e7-9dbd-cb7e8a065bcb.png)

**Comment by vaimdev** [comment]
Hi , I checked in the database , it was the old data that created due to bug. Topic name is blank. Now it should work properly. I can update the Topic name with some value then you should not see this problem anymore

**Comment by vaimdev** [comment]
I have put a value in the blank topic name, you may verify again.

**Comment by sabrinasun** [comment]
That looks good. Can we add a margin-right: 5px to the topic and remove &nbsp space. In this way no leading space will be displayed  for any lines of of topics, since margin will always stay behind the topic word. 
![topic space](https://cloud.githubusercontent.com/assets/877632/24386742/40cef25e-133f-11e7-9bcb-e907dfc6f3eb.png)

**Comment by vaimdev** [comment]
Ok, item fixed and updated to test site

**Comment by sabrinasun** [comment]
fixed
