### ISSUE TITLE
Text form throws exception when update pdf with a very long file name or if with chinese name 

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#59]
Not sure if there is an easy way to handle, to give a better validation message at least. If can't even prompt validation error, we need to add a message in the form 
Extended: Add additional information to give your content more exposure. All Optional.
                 Please make sure the file name is shorter than 50 letters and contains letters and digits only.

Get exception when file name is too long
DataError at /timeline/timelineitem/16/edit/sharetext
value too long for type character varying(50)
Request Method:	POST
Request URL:	http://djangoupgrade.buddhistexchange.com/timeline/timelineitem/16/edit/sharetext
Django Version:	1.10.5
Exception Type:	DataError
Exception Value:	
value too long for type character varying(50)
Exception Location:	/home/befree/.virtualenvs/be_upgrade/lib/python3.5/site-packages/django/db/backends/utils.py in execute, line 64
Python Executable:	/usr/local/bin/python3
Python Version:	3.5.2
Python Path:	
['/home/befree/webapps/be_djangoupgrade',
 '/home/befree/webapps/be_djangoupgrade/myproject',
 '/home/befree/.virtualenvs/be_upgrade/lib/python3.5/site-packages',
 '/usr/local/lib/python35.zip',
 '/usr/local/lib/python3.5',
 '/usr/local/lib/python3.5/plat-linux',
 '/usr/local/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/site-packages']
Server time:	Sun, 19 Mar 2017 10:56:37 -0500

Get exception with chinese file name, not sure if there is an easy fix. 
UnicodeEncodeError at /timeline/timelineitem/16/edit/sharetext
'ascii' codec can't encode characters in position 84-110: ordinal not in range(128)
Request Method:	POST
Request URL:	http://djangoupgrade.buddhistexchange.com/timeline/timelineitem/16/edit/sharetext
Django Version:	1.10.5
Exception Type:	UnicodeEncodeError
Exception Value:	
'ascii' codec can't encode characters in position 84-110: ordinal not in range(128)
Exception Location:	/usr/local/lib/python3.5/genericpath.py in exists, line 19
Python Executable:	/usr/local/bin/python3
Python Version:	3.5.2
Python Path:	
['/home/befree/webapps/be_djangoupgrade',
 '/home/befree/webapps/be_djangoupgrade/myproject',
 '/home/befree/.virtualenvs/be_upgrade/lib/python3.5/site-packages',
 '/usr/local/lib/python35.zip',
 '/usr/local/lib/python3.5',
 '/usr/local/lib/python3.5/plat-linux',
 '/usr/local/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/site-packages']
Server time:	Sun, 19 Mar 2017 10:54:34 -0500

**Comment by vaimdev** [comment]
Hi Sabrina, for long filename , I have fixed. But for Chinese file name , I cannot reproduce the error because not happen in my local. Any traceback that I can see ?

**Comment by vaimdev** [comment]
Hi, I have confirmed this issue is not programming but the OS locale issue.
https://community.webfaction.com/questions/6256/uploading-files-with-non-ascii-filenames
I have fixed it anyway.

**Comment by sabrinasun** [comment]
Sorry didn't reply promptly. Should check my emails. 
Thanks.
