### ISSUE TITLE
Peronal home page - Send a Note button clicked, see nothing

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#61]
When clicked on Send a Note, are we supposed to open the message page, Saying Send a Note to Grace... ？I can't see anything happen when click on this button.

**Comment by vaimdev** [comment]
This could be javascript problem , will look into it.

**Comment by vaimdev** [comment]
Fixed and updated to server

**Comment by sabrinasun** [comment]
Good, close now.
