### ISSUE TITLE
Topics doesn't change according to selected language. 

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#62]
Topics in all languages are always displayed, regardless of the selected language. 
Only topics for selected language should be displayed.

**Comment by vaimdev** [comment]
Noted and will work on it

**Comment by sabrinasun** [comment]
Can we add a margin right to the topic and remove &npsb; 
![topic space](https://cloud.githubusercontent.com/assets/877632/24386742/40cef25e-133f-11e7-9bcb-e907dfc6f3eb.png)

**Comment by vaimdev** [comment]
1 Question , currently the Post with different language can use same topic .

For example 
Post 1 : Language : Chinese , Topic : ABC
Post 2 : Language : English , Topic : ABC

If user choose Language English, Topic: ABC will show

However, there is a "count" for the posts under Topic : ABC , what is the count to be shown , 1 or 2 ?

**Comment by sabrinasun** [comment]
It is unlikely that people post an article in Chinese and list English topic.  Let's consider compasion and 慈悲are two different topics. For your question about count,the count is 2, but it is unlikely people put in English topic for a Chinese article.  Each topic does have a language attribute in the database though. Hope user don't put in English word as Chinese language, for now we don't need validation.

**Comment by vaimdev** [comment]
Ok, I have fixed it and updated to test site

**Comment by sabrinasun** [comment]
looks like working now, my question about how is this implemented is addressed in another email.
