### ISSUE TITLE
Post need to support line break and link

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#63]
Per conversation on the skype, please support break and link
Enter post content:
test 
test 
http://www.test.com 

It is displayed as 
test test http://www.test.com 
link is displayed at text not link. There is a tag in django that will turn http://www.test.com into 
<a href="http://www.test.com">http://www.test.com</a>
The other developer's code has used this tag.

**Comment by vaimdev** [comment]
Fixed and updated to test site, please check , thanks.
