### ISSUE TITLE
Please add link to title in stand alone link post

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#64]
User can go to the link in post list page, but in the stand alone page, the title doesn't have a link.  Please add link to the post title in standalone post page as well.

**Comment by vaimdev** [comment]
What link need to add? The link to post list?

**Comment by sabrinasun** [comment]
This page is a link post:
http://djangoupgrade.buddhistexchange.com/timeline/timelineitem/31/detail

In post list, you can go to the link test.com by clicking on 
test the stand alone link page 

But if you go to the stand alone page by clicking on Comment link, you can't access the link.  test the stand alone link page  is plain text, not clickable.

**Comment by sabrinasun** [comment]
fixed
