### ISSUE TITLE
Please give remove the white border on cart icon

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#65]
I have no idea why the cart has some white border now, probably related to css changes and fix is easy. Add a background style to cart-menu,  instead of red say:
background-color : #336699 !important
Need !important for hover effect, as long as the white border doesn't show is fine. 
![fix cart icon background](https://cloud.githubusercontent.com/assets/877632/24579872/061e2f22-16cc-11e7-9928-b9cc120db913.png)

**Comment by vaimdev** [comment]
Ok, will work on it
