### ISSUE TITLE
white background color shows when there are too  many lists

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#66]
Not sure how this happened and don't have a quite fix. Can we make the light background color goes  all the way to the bottom of the page. 
![pagebackground](https://cloud.githubusercontent.com/assets/877632/24579956/b9d420ca-16cd-11e7-9ec4-76985bc73864.png)

**Comment by vaimdev** [comment]
I try to adjust but no luck also, will come back again

**Comment by sabrinasun** [comment]
Please remove the height: 100% style, and add <div style="clear:both"></div> as shown below, should fix it.
![content background](https://cloud.githubusercontent.com/assets/877632/24735565/8d66577e-1a51-11e7-908b-fafb0f44634e.png)

**Comment by vaimdev** [comment]
Ok, i'll try to adjust it again though I have tried in Firefox but no luck.

**Comment by sabrinasun** [comment]
it works for me in firefox too. The fix should be compatible across browsers. 
need to add the clear:both div, that is critical. When divs float, need to add empty div with clear:both at the end. Also remove height:100% style.

**Comment by vaimdev** [comment]
Yes, I have tested, it works. Thanks.
