### ISSUE TITLE
Javascript error when submit a comment

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#77]
login, then to to page:
http://djangoupgrade.buddhistexchange.com/timeline/timelineitem/36/detail
enter a comment and click submit. Javascript error in console:
detail:207 Uncaught ReferenceError: PostForm is not defined
    at HTMLAnchorElement.onclick (detail:207)

**Comment by vaimdev** [comment]
Hi, I cannot reproduce the error . I login with my id , sending comment "testing", no error.

**Comment by sabrinasun** [comment]
It is actually not hard to reproduce. If the first time can submit, try a second time. I don't know why sometimes submission is ok, but 9 out of 10 times will throw the error. 
Here is the screenshot of the error in ie and chrome. Do you know where is PostForm defined? A simple submit button should do it, why use PostForm.xxx? 
![ie-submitcomment](https://cloud.githubusercontent.com/assets/877632/24935814/5710b89a-1ef2-11e7-97d3-e94b8d915510.png)
![chrome-submitcomment](https://cloud.githubusercontent.com/assets/877632/24935815/59493f24-1ef2-11e7-86cf-86c5d16d11e4.png)
