### ISSUE TITLE
Post selected Chinese as language is not visible to visitors even though All is selected. 

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#78]
There are two issues：
1. User has Chinese in settings. Create a post and select Chinese in language dropdown for this post. 
Log out. 
Now even though the language All is selected, this post is not displayed.

2. Click on the language dropdown, Chinese is not displayed.

**Comment by vaimdev** [comment]
Hi, I saw there are 3 languages in db , which is "中文", "English" & "Chinese" , which one is the "Chinese" you mean in this bug ?

**Comment by sabrinasun** [comment]
Oh I added "中文" by mistake. That is not used. Chinese is Chinese. 
I don't think the database table is used at all, additional entry "中文" in the database doesn't show up in the dropdown.

**Comment by sabrinasun** [comment]
Type in below address in browser 
http://djangoupgrade.buddhistexchange.com/
It redirects to 
http://djangoupgrade.buddhistexchange.com/en/
But the dropdown still has only English.

**Comment by vaimdev** [comment]
Hi, I think I make mistake , I thought the drop down only need to show English. 
To double confirm
1. For user not authenticated, drop down show all languages , default as English
2. For user authenticated, drop down show all languages maintained in their profile, default as first language in profile

Is it correct ?

**Comment by sabrinasun** [comment]
Remaining issue: 
When click on language dropdown all, it shows only English, no chinese. I really don't know how useful All option is, we can remove it if that is easy.

**Comment by vaimdev** [comment]
Fixed in the latest update on test site. 
"All" are removed from the drop down now.
