### ISSUE TITLE
User can't see any topics without login first.

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#83]
This is an issue in production site. It is good in test site. 
If user has Chinese language setup, should see the topics: 
所有主题
诗歌 现代往生录 无常 念佛 净土 出离心
However, after user log out, no topic is displayed.

**Comment by sabrinasun** [comment]
Actually as I further check, if user is not login, only English keywords are displayed, not chinese keywords, even when switched to Chinese.

**Comment by vaimdev** [comment]
Fixed. Some mixing of keyword in both English and Chinese are caused by some posts in chinese use english keyword and vice versa
