### ISSUE TITLE
a missing feather: display the keyword for each post

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#86]
In the specs, the keywords are displayed below each post and when clicked, will bring out all the posts under this keyword. This is not implemented. See retreat and meditation below. 
![keywords](https://cloud.githubusercontent.com/assets/877632/25769387/5cff4c92-31e6-11e7-8b94-8f9250bc6ea9.png)

**Comment by vaimdev** [comment]
Changes included in the url enhancement changes.
