### ISSUE TITLE
Exception when clicks on All Topics

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#87]
Go to Sabrina's Dharma Page
http://www.buddhistexchange.com/zh-hans/network/user/12/
Click on All Topics and get exception: 
ValueError at /zh-hans/network/user/12/
invalid literal for int() with base 10: 'all'
Request Method:	GET
Request URL:	http://www.buddhistexchange.com/zh-hans/network/user/12/?topic=all&language=&category=
Django Version:	1.10.5
Exception Type:	ValueError
Exception Value:	
invalid literal for int() with base 10: 'all'
Exception Location:	/home/befree/.virtualenvs/befree/lib/python3.5/site-packages/django/db/models/fields/__init__.py in get_prep_value, line 946
Python Executable:	/home/befree/.virtualenvs/befree/bin/python3
Python Version:	3.5.2
Python Path:	
['/home/befree/webapps/buddhistexchange_app_new',
 '/home/befree/webapps/buddhistexchange_app_new/myproject',
 '/home/befree/.virtualenvs/befree/lib/python35.zip',
 '/home/befree/.virtualenvs/befree/lib/python3.5',
 '/home/befree/.virtualenvs/befree/lib/python3.5/plat-linux',
 '/home/befree/.virtualenvs/befree/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5',
 '/usr/local/lib/python3.5/plat-linux',
 '/home/befree/.virtualenvs/befree/lib/python3.5/site-packages']
Server time:	星期六, 6 五月 2017 15:44:41 -0500

**Comment by vaimdev** [comment]
Noted on the bug. will fix.

**Comment by vaimdev** [comment]
Already fixed and included in the last update in the roll out.
