### ISSUE TITLE
A few issues with language

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#88]
This page is a bit strange:
http://www.buddhistexchange.com/zh-hans/home?topic=11&category=&language=2&usertype=everyone
I dont't understand why there are two language related params: zh-hans and language = 2
Which one does the language go by? 
How is /en/ in url parameter and query string used differetly:
1. if you click on dropdown on the top right corner, it sends query string.
2. if you login (account set up chinese language)and change the dropdown to Chinese, click on either topics link or the form link, /en/ is changed to zh-hans. **If you click on Buddhist Exchange or 家，it goes back to English. Are we keeping this in session so that unless user switch combo, language stays the same? Sounds a bit messy, somehow language is hardcoded into the link for 家and Buddhist　Exchange.**
3. Try this sequence and you will see the wiered page with en and language = 2 http://www.buddhistexchange.com/en/home?language=2&category=&topic=11&usertype=everyone
go to home page - language is english
login to an account that has chinese, page is english
click on any english topic, displayed fine
click on Chinese in the language dropdown menu, you get a page with Chinese categories and topics, but without any content. because content is getting langauge setting from /en/, and menu/category/topics is getting from query string. 
http://www.buddhistexchange.com/en/home?language=2&category=&topic=11&usertype=everyone

**Comment by vaimdev** [comment]
The url is production url , I believe they are not issue on test site.

**Comment by sabrinasun** [comment]
fixed.
