### ISSUE TITLE
strange url

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#89]
type in http://djangoupgrade.buddhistexchange.com/
it goes to
http://djangoupgrade.buddhistexchange.com/en/
Select Chinese language, it goes to 
http://djangoupgrade.buddhistexchange.com/en/timeline/all/all/?usertype=everyone&language=2
Select English language, it goes to
http://djangoupgrade.buddhistexchange.com/zh-hans/timeline/all/all/?usertype=everyone&language=1

**Comment by vaimdev** [comment]
I'll double check

**Comment by sabrinasun** [comment]
looks good.
