### ISSUE TITLE
Exception when going to a user's dharma page. 

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#90]
Now click on ystw link in the post, which is
http://djangoupgrade.buddhistexchange.com/en/network/user/135/
Receive exception 
NoReverseMatch at /en/network/user/135/
Reverse for 'user_public_list' with arguments '(135, 'all', 'previously-blank')' and keyword arguments '{}' not found. 1 pattern(s) tried: ['en/network/user/(?P<pk>\\d+)/(?P<category_slug>\\w+)/(?P<topic_slug>\\w+)/$']
Request Method:	GET
Request URL:	http://djangoupgrade.buddhistexchange.com/en/network/user/135/
Django Version:	1.10.5
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for 'user_public_list' with arguments '(135, 'all', 'previously-blank')' and keyword arguments '{}' not found. 1 pattern(s) tried: ['en/network/user/(?P<pk>\\d+)/(?P<category_slug>\\w+)/(?P<topic_slug>\\w+)/$']
Exception Location:	/home/befree/.virtualenvs/be_upgrade/lib/python3.5/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 392
Python Executable:	/usr/local/bin/python3
Python Version:	3.5.2
Python Path:	
['/home/befree/webapps/be_djangoupgrade',
 '/home/befree/webapps/be_djangoupgrade/myproject',
 '/home/befree/.virtualenvs/be_upgrade/lib/python3.5/site-packages',
 '/usr/local/lib/python35.zip',
 '/usr/local/lib/python3.5',
 '/usr/local/lib/python3.5/plat-linux',
 '/usr/local/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/site-packages']
Server time:	Mon, 15 May 2017 20:34:59 -0500

**Comment by vaimdev** [comment]
Fixed.
