### ISSUE TITLE
In production, registered user is not getting an email. User can't register. = production

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#92]
After user registration, an email should be sent to the user's email box, with activation link. 
User can't get this email. This used to work. 
The same happens in test site. Since 5/7 user can't login. They are not receiving activation email. 

![registration](https://cloud.githubusercontent.com/assets/877632/26284919/b8ba0566-3e13-11e7-89b0-a6b7ff258815.png)

**Comment by vaimdev** [comment]
Hi, I just tested on test site, I managed to register and received the activation email.

==========

Dear vaiminfo,

Thank you for signing up at BuddhistExchange.com.

To activate your account you should click on the link below:

http://BuddhistExchange.com/zh-hans/activate/4bf005c835fd0fcb58ce1e63932984b5f0710fe0/

感谢使用我们的站点！

Sincerely,
BuddhistExchange.com
support@buddhistexchange.com
	
10:55 PM (0 minutes ago)

**Comment by vaimdev** [comment]
I will check in production site

**Comment by vaimdev** [comment]
I just tested on production site , I managed to get the email too.

**Comment by sabrinasun** [comment]
Sorry you are right email is sent. Need a message
