### ISSUE TITLE
Exception when contact user = production

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#93]
In the production site, the contact form is not working in any way. 
A simple way to bring out contact form, is first login, then add a book to cart, then click on cart button to check out. Now there is a link to contact the book giver. Click on it, in the popup enter message and submit. 

TypeError at /en/contact_user/
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Request Method:	GET
Request URL:	http://djangoupgrade.buddhistexchange.com/en/contact_user/
Django Version:	1.10.5
Exception Type:	TypeError
Exception Value:	
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Exception Location:	/home/befree/webapps/be_djangoupgrade/myproject/core/views.py in contact_user, line 273
Python Executable:	/home/befree/.virtualenvs/be_upgrade/bin/python3
Python Version:	3.5.2
Python Path:	
['/home/befree/webapps/be_djangoupgrade',
 '/home/befree/webapps/be_djangoupgrade/myproject',
 '/home/befree/.virtualenvs/be_upgrade/lib/python35.zip',
 '/home/befree/.virtualenvs/be_upgrade/lib/python3.5',
 '/home/befree/.virtualenvs/be_upgrade/lib/python3.5/plat-linux',
 '/home/befree/.virtualenvs/be_upgrade/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5',
 '/usr/local/lib/python3.5/plat-linux',
 '/home/befree/.virtualenvs/be_upgrade/lib/python3.5/site-packages']
Server time:	Sun, 21 May 2017 10:01:52 -0500

**Comment by vaimdev** [comment]
Hi , I just tested on test site , no issue for this, it could be the javascript does not get the correct user_id , and does not append the ?user_id=xx at the end of URL.

What browser you used to test ? Try to clear cache and test again. 

By the way, accessing http://djangoupgrade.buddhistexchange.com/en/contact_user/ directly will cause exception (bug from the old code) , I have enhanced the code to avoid throwing this exception .

**Comment by sabrinasun** [comment]
I am in chrome and IE. When click on the link, it does append user id. The submission link does't have user id. I can always reproduce. I cleared cache and still see the same, already get exception.

**Comment by vaimdev** [comment]
Hi, I double check this issue in the code, there is not issue with the code , most probably is data problem.  
The submission link use javascript , 

       <a href="javascript:void(0)" class="add-another"
          onclick="javascript: window.open('{% url 'contact_user' %}**?user_id={{order.giver.id}}',**  'winname','directories=no,titlebar=no,toolbar=no,location=no,status=no,menubar=no,scrollbars=no,resizable=no,width=450,height=280, left=200, top=60');">Contact Giver **{{ order.giver.profile.get_display_name }}**</a>

I tried with Chrome , no issue also. 
If you have javascript error on that page , do let me know.

**Comment by vaimdev** [comment]
ok, I think I am able to reproduce the error , will check

**Comment by vaimdev** [comment]
Fixed

**Comment by sabrinasun** [comment]
fixed in test site.
