### ISSUE TITLE
MOBILE - in stand alone page, the post is wider than screen width

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#99]
![image](https://user-images.githubusercontent.com/877632/27997689-e1b77672-64cb-11e7-812b-afe93ba61f0a.png)

**Comment by vaimdev** [comment]
Hi,
I have tested in my Samsung S5 Browser, it does not have this bugs. I believe it is cache problem. May you clear the cache and try again ?

**Comment by sabrinasun** [comment]
Thanks, fixed.
